// frontend/src/app/(protected)/dashboard/page.tsx
import { getTodos } from "@/lib/actions/todos";

export default async function DashboardPage() {
  const todos = await getTodos();

  // 完了/未完了のタスクを分ける
  const incompleteTodos = todos.filter(todo => !todo.completed);
  const completedTodos = todos.filter(todo => todo.completed);

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-7xl mx-auto">
        {/* ヘッダーエリア */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            ダッシュボード
          </h1>
          <p className="text-gray-600">
            今日のタスクと進捗状況を確認しましょう
          </p>
        </div>

        {/* 統計カード */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">全タスク</p>
                <p className="text-3xl font-bold text-gray-900 mt-2">
                  {todos.length}
                </p>
              </div>
              <div className="h-12 w-12 bg-blue-100 rounded-full flex items-center justify-center">
                <svg className="h-6 w-6 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                </svg>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">未完了</p>
                <p className="text-3xl font-bold text-orange-600 mt-2">
                  {incompleteTodos.length}
                </p>
              </div>
              <div className="h-12 w-12 bg-orange-100 rounded-full flex items-center justify-center">
                <svg className="h-6 w-6 text-orange-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">完了</p>
                <p className="text-3xl font-bold text-green-600 mt-2">
                  {completedTodos.length}
                </p>
              </div>
              <div className="h-12 w-12 bg-green-100 rounded-full flex items-center justify-center">
                <svg className="h-6 w-6 text-green-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
            </div>
          </div>
        </div>

        {/* タスク一覧 */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* 未完了タスク */}
          <div className="bg-white rounded-lg shadow">
            <div className="p-6 border-b border-gray-200">
              <h2 className="text-xl font-semibold text-gray-900">
                未完了のタスク
              </h2>
            </div>
            <div className="p-6">
              {incompleteTodos.length === 0 ? (
                <p className="text-gray-500 text-center py-8">
                  未完了のタスクはありません
                </p>
              ) : (
                <ul className="space-y-3">
                  {incompleteTodos.slice(0, 5).map((todo) => (
                    <li
                      key={todo.id}
                      className="flex items-start p-3 hover:bg-gray-50 rounded-lg transition-colors"
                    >
                      <div className="flex-shrink-0 mt-1">
                        <div className="h-5 w-5 rounded border-2 border-gray-300"></div>
                      </div>
                      <div className="ml-3 flex-1">
                        <p className="text-sm font-medium text-gray-900">
                          {todo.title}
                        </p>
                        {todo.description && (
                          <p className="text-sm text-gray-500 mt-1">
                            {todo.description}
                          </p>
                        )}
                      </div>
                    </li>
                  ))}
                </ul>
              )}
              {incompleteTodos.length > 5 && (
                <div className="mt-4 text-center">
                  <a href="/todos" className="text-sm text-blue-600 hover:text-blue-700 font-medium">
                    すべて表示 ({incompleteTodos.length}件)
                  </a>
                </div>
              )}
            </div>
          </div>

          {/* 完了済みタスク */}
          <div className="bg-white rounded-lg shadow">
            <div className="p-6 border-b border-gray-200">
              <h2 className="text-xl font-semibold text-gray-900">
                完了済みタスク
              </h2>
            </div>
            <div className="p-6">
              {completedTodos.length === 0 ? (
                <p className="text-gray-500 text-center py-8">
                  完了済みのタスクはありません
                </p>
              ) : (
                <ul className="space-y-3">
                  {completedTodos.slice(0, 5).map((todo) => (
                    <li
                      key={todo.id}
                      className="flex items-start p-3 hover:bg-gray-50 rounded-lg transition-colors"
                    >
                      <div className="flex-shrink-0 mt-1">
                        <div className="h-5 w-5 rounded bg-green-500 flex items-center justify-center">
                          <svg className="h-3 w-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                          </svg>
                        </div>
                      </div>
                      <div className="ml-3 flex-1">
                        <p className="text-sm font-medium text-gray-500 line-through">
                          {todo.title}
                        </p>
                        {todo.description && (
                          <p className="text-sm text-gray-400 mt-1 line-through">
                            {todo.description}
                          </p>
                        )}
                      </div>
                    </li>
                  ))}
                </ul>
              )}
              {completedTodos.length > 5 && (
                <div className="mt-4 text-center">
                  <a href="/todos" className="text-sm text-blue-600 hover:text-blue-700 font-medium">
                    すべて表示 ({completedTodos.length}件)
                  </a>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend-nuxt/app/pages/dashboard/index.vue
<script setup lang="ts">
const today = new Date()
const dateStr = `${today.getMonth() + 1}月 ${today.getDate()}日 ${['日', '月', '火', '水', '木', '金', '土'][today.getDay()]}曜日`

// APIからデータを取得
const { data: tasks } = await useFetch('/api/tasks')
const { data: sprints } = await useFetch('/api/sprints')

const toggleTask = (taskId: number) => {
  if (!tasks.value) return
  const task = tasks.value.find(t => t.id === taskId)
  if (task) {
    task.completed = !task.completed
  }
}

const addTask = () => {
  console.log('タスクを追加')
}

const addProject = () => {
  console.log('スプリントを追加')
}
</script>

<template>
  <div class="w-full py-8 px-4 lg:px-8">
    <div class="max-w-6xl">
      <!-- ウェルカムセクション -->
      <div class="mb-8">
        <p class="text-sm text-gray-400 mb-2">{{ dateStr }}</p>
        <h1 class="text-3xl font-bold text-white mb-4">keiji さん、こんばんは</h1>

        <div class="flex items-center gap-4">
          <button class="px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded-lg text-sm text-gray-300 transition-colors">
            週 ▼
          </button>
          <div class="flex items-center gap-2 text-sm text-gray-400">
            <span>✓ 0 件のタスクが完了しました</span>
            <span>👥 0 人のコラボレーター</span>
          </div>
          <button class="ml-auto px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded-lg text-sm text-gray-300 transition-colors">
            カスタマイズ
          </button>
        </div>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <!-- マイタスクセクション -->
        <div class="bg-gray-800 rounded-lg p-6 border border-gray-700">
          <div class="flex items-center gap-3 mb-6">
            <div class="w-12 h-12 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center">
              <span class="text-white text-xl">👤</span>
            </div>
            <div>
              <h2 class="text-xl font-semibold text-white flex items-center gap-2">
                マイタスク
                <svg class="w-4 h-4 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                </svg>
              </h2>
              <div class="flex gap-4 text-sm text-gray-400 mt-1">
                <button class="hover:text-white transition-colors">今日</button>
                <button class="hover:text-white transition-colors">期限超過 (4)</button>
                <button class="hover:text-white transition-colors">完了</button>
              </div>
            </div>
          </div>

          <!-- タスクリスト -->
          <div class="space-y-2 mb-4">
            <div
              v-for="task in tasks"
              :key="task.id"
              class="flex items-center gap-3 p-2 rounded hover:bg-gray-700 transition-colors group"
            >
              <button
                @click="toggleTask(task.id)"
                :class="[
                  'w-5 h-5 rounded border-2 transition-colors flex-shrink-0',
                  task.completed
                    ? 'bg-green-500 border-green-500'
                    : 'border-gray-500 hover:border-gray-400',
                ]"
              >
                <svg
                  v-if="task.completed"
                  class="w-full h-full text-white"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="3"
                    d="M5 13l4 4L19 7"
                  />
                </svg>
              </button>
              <span :class="['flex-1 text-gray-300', task.completed ? 'line-through opacity-50' : '']">
                {{ task.title }}
              </span>
              <span class="text-xs px-2 py-1 bg-purple-500/20 text-purple-300 rounded">
                {{ task.tag }}
              </span>
              <button class="opacity-0 group-hover:opacity-100 text-gray-500 hover:text-white transition-all">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z" />
                </svg>
              </button>
            </div>
          </div>

          <button
            @click="addTask"
            class="text-sm text-gray-400 hover:text-white transition-colors"
          >
            + タスクを作成
          </button>

          <button class="mt-4 text-sm text-gray-400 hover:text-white transition-colors">
            もっと表示
          </button>
        </div>

        <!-- スプリントセクション -->
        <div class="bg-gray-800 rounded-lg p-6 border border-gray-700">
          <div class="flex items-center justify-between mb-6">
            <h2 class="text-xl font-semibold text-white">スプリント</h2>
            <button class="text-sm text-gray-400 hover:text-white transition-colors">
              最近 ▼
            </button>
          </div>

          <!-- スプリント追加ボタン -->
          <button
            @click="addProject"
            class="w-full p-4 mb-4 border-2 border-dashed border-gray-700 rounded-lg hover:border-gray-600 transition-colors"
          >
            <div class="flex items-center justify-center gap-2 text-gray-400">
              <span class="text-2xl">+</span>
              <span class="text-sm">スプリントを作成</span>
            </div>
          </button>

          <!-- スプリントカード -->
          <div class="space-y-3">
            <div
              v-for="project in sprints"
              :key="project.id"
              class="p-4 bg-gray-700/50 rounded-lg hover:bg-gray-700 transition-colors cursor-pointer group"
            >
              <div class="flex items-center gap-3">
                <div :class="['w-8 h-8 rounded flex items-center justify-center', project.color]">
                  <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                  </svg>
                </div>
                <span class="flex-1 font-medium text-white">{{ project.name }}</span>
                <button class="opacity-0 group-hover:opacity-100 text-gray-500 hover:text-white transition-all">
                  <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z" />
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- 非公開のメモ帳セクション -->
      <div class="mt-6 bg-gray-800 rounded-lg p-6 border border-gray-700">
        <div class="flex items-center justify-between mb-4">
          <h2 class="text-xl font-semibold text-white flex items-center gap-2">
            非公開のメモ帳
            <svg class="w-5 h-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
            </svg>
          </h2>
          <button class="text-gray-500 hover:text-white transition-colors">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <p class="text-gray-400 text-sm mb-4">
          簡単なメモや重要な参考資料へのリンクを追加しましょう。
        </p>
        <textarea
          class="w-full bg-gray-900 border border-gray-700 rounded-lg p-3 text-gray-300 placeholder-gray-500 focus:outline-none focus:border-gray-600 resize-none"
          rows="3"
          placeholder="メモを入力..."
        />
      </div>
    </div>
  </div>
</template>
