// frontend/src/app/(protected)/todos/page.tsx
import { getTodos } from "../../../../lib/actions/todos";

export default async function TodosPage() {
  const todos = await getTodos();

  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-100 p-8">
      <div>
        <h1 className="text-4xl font-bold text-gray-800 mb-6">
          Todos
        </h1>

        <ul className="space-y-4">
          {todos.map((todo) => (
            <li key={todo.id} className="p-4 bg-white rounded shadow">
              <h2 className="text-xl font-semibold">{todo.title}</h2>
              <p className="text-gray-600">{todo.description}</p>
              <span className="text-sm text-gray-400">
                Completed: {todo.completed ? "Yes" : "No"}
              </span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

// frontend-nuxt/app/pages/todos/index.vue
<script lang="ts" setup>
import type { components } from "../../../types/api.d.ts"

type Todo = components["schemas"]["model.Todo"]

const todos = ref<Todo[]>([])

const fetchTodos = async () => {
  try {
    const data = await $fetch<Todo[]>('/api/todos')
    console.log(data)
    todos.value = data
  }
  catch (error) {
    console.error('Error fetching TODOs:', error)
  }
}
await fetchTodos()
</script>

<template>
  <h1 class="text-2xl font-bold mb-4">TODO</h1>
  <p>TODO一覧です</p>
  <ul class="mt-4 space-y-2">
    <li
      v-for="todo in todos"
      :key="todo.id"
      class="p-4 border rounded shadow"
    >
      <h2 class="text-lg font-semibold">{{ todo.title }}</h2>
      <p class="text-gray-600">{{ todo.description }}</p>
      <p class="text-sm text-blue-500">Status: {{ todo.completed ? 'Completed' : 'Pending' }}</p>
    </li>
  </ul>
</template>
