// frontend/src/app/(auth)/login/page.tsx
"use client"

import { useState } from "react"
import { login } from "../../../../lib/actions/auth"
import { useRouter } from "next/navigation"
import { AuthenticationError } from "../../../../lib/api/error"

export default function LoginPage() {
  const [error, setError] = useState("")
  const [loading, setLoading] = useState(false)
  const router = useRouter()

  const [username, setUsername] = useState("testuser")
  const [password, setPassword] = useState("password123")

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    setError("")
    setLoading(true)

    const formData = new FormData(e.currentTarget)

    try {
      await login({
        username: formData.get("username") as string,
        password: formData.get("password") as string,
      })

      // ログイン成功後、ダッシュボードにリダイレクト
      router.push("/dashboard")
    }
    catch (err) {
      if (err instanceof AuthenticationError) {
        setError("ユーザー名またはパスワードが正しくありません")
      }
      else {
        setError("ログインに失敗しました。もう一度お試しください。")
      }
      console.error("Login error:", err)
    }
    finally {
      setLoading(false)
    }
  }

  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-100 p-4">
      <div className="w-full max-w-md bg-white rounded-lg shadow-md p-8">
        <h1 className="text-2xl font-bold text-gray-800 mb-6 text-center">
          Retro Todo App
        </h1>
        <h2 className="text-xl font-semibold text-gray-700 mb-6 text-center">
          ログイン
        </h2>

        {error && (
          <div className="mb-4 p-3 bg-red-100 border border-red-400 text-red-700 rounded">
            {error}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label htmlFor="username" className="block text-sm font-medium text-gray-700 mb-1">
              ユーザー名
            </label>
            <input
              id="username"
              name="username"
              type="text"
              required
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-black"
              placeholder="username"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              disabled={loading}
            />
          </div>

          <div>
            <label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-1">
              パスワード
            </label>
            <input
              id="password"
              name="password"
              type="password"
              required
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-black"
              placeholder="••••••••"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              disabled={loading}
            />
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded-md transition-colors disabled:bg-blue-400 disabled:cursor-not-allowed"
          >
            {loading ? "ログイン中..." : "ログイン"}
          </button>
        </form>

        <div className="mt-6 text-center">
          <p className="text-sm text-gray-600">
            アカウントをお持ちでない方は{" "}
            <a href="/register" className="text-blue-600 hover:underline">
              新規登録
            </a>
          </p>
        </div>

        <div className="mt-4 text-center">
          <p className="text-xs text-gray-500">
            テストユーザー: myuser / password123
          </p>
        </div>
      </div>
    </div>
  )
}

// frontend-nuxt/app/pages/(auth)/login.vue
<script setup lang="ts">
import BaseButton from '~/components/ui/BaseButton.vue'

definePageMeta({
  layout: 'auth',
})

const config = useRuntimeConfig()

const { login } = useAuth()
const router = useRouter()

const username = ref('')
const password = ref('')
const isLoading = ref(false)
const errorMessage = ref('')

// TODO: リリース前には除去する
const setSampleCredentials = () => {
  username.value = 'testuser'
  password.value = 'password123'
}

const onSubmit = async () => {
  if (!username.value || !password.value) {
    errorMessage.value = 'ユーザー名とパスワードを入力してください'
    return
  }

  isLoading.value = true
  errorMessage.value = ''

  try {
    const result = await login({
      username: username.value,
      password: password.value,
    })

    console.log('Login result:', result) // デバッグ用

    if (result && result.success) {
      await router.push('/dashboard')
    }
    else {
      errorMessage.value = (result && result.error) || 'ログインに失敗しました'
    }
  }
  catch (error) {
    console.error('ログインエラー:', error)
    errorMessage.value = 'ログイン処理中にエラーが発生しました'
  }
  finally {
    isLoading.value = false
  }
}

const continueWithGoogle = () => {
  // TODO: Google OAuth実装
  console.log('Google OAuth is not implemented yet')
}
</script>

<template>
  <div class="min-h-screen flex flex-col">
    <!-- <main class="flex-1 flex items-center justify-center"> -->
      <div class="w-full max-w-md text-center px-4">
        <h1 class="text-3xl font-semibold mb-2">
          {{ config.public.appName }}へようこそ
        </h1>
        <p class="text-gray-500 mb-8">
          まずはサインインしてください
        </p>

        <div class="text-dark-500 mb-8">
          テスト用アカウント
          <ul>
            <li>testuser
            </li>
            <li>password123</li>
          </ul>
        </div>

        <!-- Googleで続行 -->
        <button
          type="button"
          @click="continueWithGoogle"
          class="w-full flex items-center justify-center border border-gray-300 rounded-md py-3 mb-6
                 hover:bg-gray-50 transition text-sm font-medium"
        >
          <span class="mr-2">
            <!-- 簡易 Google アイコン -->
            <span class="inline-block w-5 h-5 rounded-full bg-white border" />
          </span>
          <span>Google で続ける</span>
        </button>

        <!-- 区切り線 -->
        <div class="flex items-center my-4">
          <div class="flex-1 h-px bg-gray-200"></div>
          <span class="mx-4 text-xs text-gray-400">または</span>
          <div class="flex-1 h-px bg-gray-200"></div>
        </div>

        <!-- エラーメッセージ -->
        <div v-if="errorMessage" class="mb-4 p-3 bg-red-50 border border-red-200 rounded-md">
          <p class="text-sm text-red-600">{{ errorMessage }}</p>
        </div>
  
        <div>
          <BaseButton class="mb-4" @click="setSampleCredentials">
            テスト用アカウントのID / PWを入力
          </BaseButton>
        </div>

        <!-- ログインフォーム -->
        <form @submit.prevent="onSubmit" class="mt-4">
          <div class="mb-4 text-left">
            <label class="block text-xs font-medium text-gray-600 mb-1">
              ユーザー名
            </label>
            <input
              v-model="username"
              type="text"
              required
              :disabled="isLoading"
              class="block w-full border border-gray-300 rounded-md px-3 py-2 text-sm
                     focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500
                     disabled:bg-gray-100 disabled:cursor-not-allowed"
            />
          </div>

          <div class="mb-4 text-left">
            <label class="block text-xs font-medium text-gray-600 mb-1">
              パスワード
            </label>
            <input
              v-model="password"
              type="password"
              required
              :disabled="isLoading"
              class="block w-full border border-gray-300 rounded-md px-3 py-2 text-sm
                     focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500
                     disabled:bg-gray-100 disabled:cursor-not-allowed"
            />
          </div>

          <BaseButton
            :disabled="isLoading"
            type="submit"
            class="w-full bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium
                   rounded-md py-3 mt-2 transition disabled:bg-blue-400 disabled:cursor-not-allowed"
          >
            {{ isLoading ? 'ログイン中...' : '続行' }}
          </BaseButton>
        </form>
      </div>
    <!-- </main> -->
  </div>
</template>
